#!/bin/bash

set -x

CETONI_DRIVER_NAME=ixx_driver
CETONI_DRIVER_VERSION=1.1.148.0

# Install Cetoni driver
case "$1" in
    configure)
        dkms install -m $CETONI_DRIVER_NAME -v $CETONI_DRIVER_VERSION
    ;;


    abort-upgrade|abort-remove|abort-deconfigure)
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac


# Trigger udev to reread all rules
/sbin/udevadm control --reload-rules
/sbin/udevadm trigger
