#!/bin/sh

# Verify if secure boot bios option is disabled. If not exit with error code 1
if [ ! -z "$(mokutil --sb-state | grep -i enabled)" ]; then
    echo "ERROR! Disable Secure Boot in the BIOS before installing this program" >&2
    exit 1
fi

exit 0
