#!/bin/bash


set -e
set -x

CETONI_DRIVER_NAME=ixx_driver
CETONI_DRIVER_VERSION=1.1.148.0

#Remove Cetoni drivers
case "$1" in
    remove|deconfigure)
	if [  "`dkms status -m $NAME`" ]; then
         dkms remove -m $CETONI_DRIVER_NAME -v $CETONI_DRIVER_VERSION --all
        fi
    ;;

    upgrade|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
