#!/bin/bash


set -e
set -x

#Remove Cetoni drivers
case "$1" in
    remove)
      pushd "/usr/src/ixx_driver-1.1.148.0/"
      make uninstall
      make clean
      popd
    ;;

    remove|upgrade|failed-upgrade)
    ;;

    *)
        echo "prerm called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

exit 0
